name: auto-merge-open-wa-pr

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: .github/auto-merge.yml
          command: merge
          approve: true
          target: patch
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
