# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set Username
      run: |
        git config --local user.email "shah@openwa.dev"
        git config --local user.name "GH ACTION"
        git rm -f -r .github
        git commit -m "[AUTOMATED] TRANSFER" -a
    - name: Push changes to heroku-deploy branch on main repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: deploy
        repository: open-wa/wa-automate-nodejs
        force: true
